ModernRecrut.MVC/Controllers/DocumentsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interface;
using ModernRecrut.MVC.Models;
using System.Web.Http;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize(Roles = "Candidat, Admin")]
    public class DocumentsController : Controller
    {
        private readonly IDocumentsService _documentsService;
        private readonly ILogger<DocumentsController> _logger;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<Utilisateur> _userManager;

        public DocumentsController(IWebHostEnvironment hostEnvironment, IDocumentsService documentsService,
            ILogger<DocumentsController> logger, UserManager<Utilisateur> userManager)
        {
            _documentsService = documentsService;
            _logger = logger;
            _hostEnvironment = hostEnvironment;
            _userManager = userManager;
        }

        // GET: DocumentsController
        [Authorize(Roles = "Candidat, Admin")]
        public async Task<ActionResult> Index()
        {           
            var user = await _userManager.GetUserAsync(User);
            
            if(user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié, redirection vers la page de connexion.");
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }
            
            var documents = await _documentsService.ObtenirTout(user.Id);

            return View(documents);
        }

        // GET: DocumentsController/Create
        [Authorize(Roles = "Candidat, Admin")]
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: DocumentsController/Create
        [Authorize(Roles = "Candidat, Admin")]
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DocumentModel document, IFormFile file)
        {
            var user = await _userManager.GetUserAsync(User);

            var allowedExtensions = new[] { ".doc", ".docx", ".pdf" };
            var extension = Path.GetExtension(file.FileName).ToLowerInvariant();
            if (!allowedExtensions.Contains(extension))
            {
                ModelState.AddModelError(String.Empty, "Les extension autorisés sont .doc , .pdf et .docx");
                _logger.LogError($"Erreur de création de document extension non-autorisés par l'utilisateur : {user.Id}");
                return View(document);
            }

            if (document.Type != null)
            {
                await _documentsService.Ajouter(user.Id, document.Type, file);
                _logger.LogInformation($"Document ajouté pour l'utilisateur : {user.Id}");
                return RedirectToAction(nameof(Index));
            }

            return View(document);
        }

        // GET: DocumentsController/Delete/5
        [Authorize(Roles = "Candidat, Admin")]
        public async Task<ActionResult> Delete(string chemin)
        {
            var user = await _userManager.GetUserAsync(User);

            if (chemin == null)
            {
                return NotFound();
            }

            var document = await _documentsService.ObtenirSelonChemin(user.Id, chemin);

            if (document == null)
            {
                _logger.LogWarning($"Document non trouvé pour le chemin : {chemin} et l'utilisateur : {user.Id}");
                return NotFound();
            }

            return View(document);
        }

        // POST: DocumentsController/Delete/5
        [Authorize(Roles = "Candidat, Admin")]
        [Microsoft.AspNetCore.Mvc.HttpPost]
        public async Task<ActionResult> Delete(DocumentModel document)
        {
            var user = await _userManager.GetUserAsync(User);
            await _documentsService.Supprimer(user.Id, document.Chemin);
            _logger.LogInformation($"Document supprimé : {document.Chemin} pour l'utilisateur : {user.Id}");
            return RedirectToAction(nameof(Index));
        }
    }
}

ModernRecrut.MVC/Views/Documents/Create.cshtml
@model ModernRecrut.MVC.Models.DocumentModel

@{
    ViewData["Title"] = "Ajouter";
}

<h1>Ajouter</h1>

<h4>Nouveau document</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-controller="Documents" asp-action="Create">
            <div class="form-group">
                <label>Type de Document</label>
                <select asp-for="Type" class="form-control">
                    <option value="CV">CV</option>
                    <option value="LettreDeMotivation">Lettre de Motivation</option>
                    <option value="Diplomes">Diplômes</option>
                </select>
            </div>
            <div class="form-group">
                <label>Télécharger Document</label>
                <input type="file" name="file" class="form-control accept=application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"/>
            </div>
            <input type="submit" value="Enregistrer" class="btn btn-primary" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModernRecrut.MVC/Views/Documents/Delete.cshtml
@model ModernRecrut.MVC.Models.DocumentModel

@{
    ViewData["Title"] = "Supprimer";
}

<h1>Supprimer</h1>

<h3>Voulez-vous vraiment supprimer ce document?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Chemin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Chemin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Type" />
        <input type="hidden" asp-for="Chemin" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

ModernRecrut.MVC/Views/Documents/Index.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.DocumentModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des documents</h1>

<p>
    <a asp-action="Create">Ajouter un nouveau document</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chemin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chemin)
            </td>
            <td>
                    <a class="btn btn-primary" href="https://localhost:7151/documents/@item.Chemin">Consulter</a> |
                    @Html.ActionLink("Supprimer", "Delete", new { chemin = item.Chemin })
            </td>
        </tr>
}
    </tbody>
</table>