ModernRecrut.MVC/Controllers/OffresEmploisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interface;
using ModernRecrut.MVC.Models;

namespace ModernRecrut.MVC.Controllers
{
    public class OffresEmploisController : Controller
    {
        private readonly IOffresEmploisService _offresEmploisService;
        private readonly ILogger<OffresEmploisController> _logger;
        private readonly UserManager<Utilisateur> _userManager;
        public OffresEmploisController(IOffresEmploisService offresEmploisService, 
            ILogger<OffresEmploisController> logger,
           UserManager<Utilisateur> userManager)
        {
            _offresEmploisService = offresEmploisService;
            _logger = logger;
            _userManager = userManager;
        }

        // GET: OffresEmploisController
        public async Task<ActionResult> Index(string searchString)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            var offresEmplois = await _offresEmploisService.ObtenirTout(user.Id);

            offresEmplois = offresEmplois.Where(e => e.DateDebut <= DateTime.UtcNow).Where(e => e.DateFin >= DateTime.UtcNow);

            //Historique d'emprunts ou emprunts en cours
            if (!String.IsNullOrEmpty(searchString))
            {
                offresEmplois = offresEmplois.Where(e => e.Poste.ToLower().Contains(searchString.ToLower()));
            }

            _logger.LogInformation($"Lecture de {offresEmplois.Count()} offres d'emplois");

            return View(offresEmplois);
        }
    

        // GET: OffresEmploisController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            var offreEmploi = await _offresEmploisService.ObtenirSelonId(id, user.Id);

            if (offreEmploi == null)
            {
                return NotFound();
            }

            return View(offreEmploi);
        }

        // GET: OffresEmploisController/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: OffresEmploisController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OffreEmploi offreEmploi)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            if (ModelState.IsValid)
            {
                await _offresEmploisService.Ajouter(offreEmploi, user.Id);

                return RedirectToAction(nameof(Index));
            }
            return View(offreEmploi);
        }

        // GET: OffresEmploisController/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            var offreEmploi = await _offresEmploisService.ObtenirSelonId(id, user.Id);

            if (offreEmploi == null)
            {
                return NotFound();
            }

            return View(offreEmploi);
        }

        // POST: OffresEmploisController/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(OffreEmploi offreEmploi)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            if (ModelState.IsValid)
            {
                await _offresEmploisService.Modifier(offreEmploi, user.Id);
                return RedirectToAction(nameof(Index));
            }
            return View(offreEmploi);
        }

        // GET: OffresEmploisController/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            var offreEmploi = await _offresEmploisService.ObtenirSelonId(id, user.Id);

            if (offreEmploi == null)
            {
                return NotFound();
            }

            return View(offreEmploi);
        }

        // POST: OffresEmploisController/Delete/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, OffreEmploi offreEmploi)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogInformation("Utilisateur non authentifié");
                user = new Utilisateur
                {
                    Id = "Anonyme",
                    Nom = "Anonyme",
                    Prenom = "Anonyme",
                    Type = "Anonyme",
                };
            }
            await _offresEmploisService.Supprimer(offreEmploi.Id, user.Id);

            return RedirectToAction(nameof(Index));
        }
    }
}

ModernRecrut.MVC/Controllers/PostulationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.DTO;
using ModernRecrut.MVC.Interface;
using ModernRecrut.MVC.Models;

namespace ModernRecrut.MVC.Controllers
{
    public class PostulationsController : Controller
    {
        private readonly UserManager<Utilisateur> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IDocumentsService _documentsService;
        private readonly IPostulationsService _postulationsService;
        private readonly INoteService _notesService;
        private readonly ILogger <PostulationsController>_logger;


        public PostulationsController(UserManager<Utilisateur> userManager,
            RoleManager<IdentityRole> roleManager,
            ILogger<PostulationsController> logger,
            IDocumentsService documentsService,
            IPostulationsService postulationsService,
            INoteService notesService)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _logger = logger;
            _documentsService = documentsService;
            _postulationsService = postulationsService;
            _notesService = notesService;
        }

        // Liste Postulation (Accessible - Employé ou Admin) - Index
        // POST: PostulationsController
        [Authorize(Roles = "Admin, RH")]
        [Authorize(Roles = "Admin, Employé")]
        public async Task<ActionResult> ListePostulations()
        {
            IEnumerable<Postulation> postulations = await _postulationsService.ObtenirTout() ?? new List<Postulation>();
            // Journalisation
            _logger.LogInformation($"Visite de la page liste des postulation par l'utilisateur {User.Identity.Name}");

            return View(postulations);
        }

        // Postuler (Accessible - Candidat ou Admin) - Create
        // POST: PostulationsController/Postuler
        [Authorize(Roles = "Admin, Candidat")]
        public ActionResult Postuler(int id)
        {
            // Journalisation
            _logger.LogInformation($"Visite de la page postuler par l'utilisateur {User.Identity.Name}");

            var userId = _userManager.GetUserId(User);

            RequetePostulation requetePostulation = new RequetePostulation
            {
                IdCandidat = userId,
                OffreDEmploiId = id,
            };

            return View(requetePostulation);
        }

        // POST: PostulationsController/Postuler
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Candidat")]
        public async Task<ActionResult> Postuler(RequetePostulation requetePostulation)
        {
            // Obtenir l'utilisateur courant
            IEnumerable<DocumentModel>? documents = _documentsService.ObtenirTout(requetePostulation.IdCandidat).Result;

            // Vérifier si l'utilisateur a un CV
            bool hasCV = false;
            foreach (var document in documents) 
            {
                if (document.Type == "CV")
                {
                    hasCV = true;
                    break;
                }
            }
            if (!hasCV)
            {
                // Si aucun CV n'est trouvé, renvoyer un message d'erreur
                ViewBag.ErrorMessage = "Un CV est requis pour postuler. Veuillez télécharger d'abord un CV dans votre espace Documents.";
                ModelState.AddModelError("Error", "Un CV est requis pour postuler. Veuillez télécharger d'abord un CV dans votre espace Documents.");
            }

            // Vérifier si l'utilisateur a une lettre de motivation
            bool hasLettreMotivation = false;
            foreach (var document in documents)
            {
                if (document.Type == "LettreDeMotivation")
                {
                    hasLettreMotivation = true;
                    break;
                }
            }
            if (!hasLettreMotivation)
            {
                // Si aucune Lettre de Motivation n'est trouvé, renvoyer un message d'erreur
                ViewBag.ErrorMessage = "Une lettre de motivation est requise pour postuler. Veuillez télécharger une lettre de motivation dans votre espace Documents.";
                ModelState.AddModelError("Error", "Une lettre de motivation est requise pour postuler. Veuillez télécharger une lettre de motivation dans votre espace Documents.");
            }

            //Vérifier si la date de disponibilité de l'utilisateur est suppérieur à la date du jour et inférieur ou égale à la date du jour + 45 joursà
            if (requetePostulation.DateDisponibilite < DateTime.Now)
            {
                // Si la date de disponibilité n'est pas valide, renvoyer un message d'erreur
                ViewBag.ErrorMessage = "La date de disponibilité doit être supérieur à la date du jour";
                ModelState.AddModelError("DateDisponibilite", "La date de disponibilité doit être supérieur ou égale à la date du jour");
            }
            if (requetePostulation.DateDisponibilite > DateTime.Now.AddDays(45))
            {
                // Si la date de disponibilité n'est pas valide, renvoyer un message d'erreur
                ViewBag.ErrorMessage = "La date de disponibilité doit être inférieur ou égale à la date du jour + 45 jours";
                ModelState.AddModelError("DateDisponibilite", "La date de disponibilité doit être inférieur ou égale à la date du jour + 45 jours");
            }

            //Vérifier si la prétention salariale est supérieur a 150 000
            if (requetePostulation.PretentionSalariale > 150000)
            {
                // Si la prétention salariale n'est pas valide, renvoyer un message d'erreur
                ViewBag.ErrorMessage = "Votre prétention salariale est au-delà de nos limites";
                ModelState.AddModelError("PretentionSalariale", "Votre prétention salariale est au-delà de nos limites");
            }

            // Verifier si on a un id de candidat
            if (String.IsNullOrEmpty(requetePostulation.IdCandidat))
            {
                ModelState.AddModelError("all", "Problème lors de l'ajout de la postulation, veuillez reessayer!");
            }

            if (ModelState.IsValid)
            {              
                //Ajouter la postulation dans la base de données
                Postulation? postulation = await _postulationsService.Ajouter(requetePostulation);
                if (postulation == null)
                {
                    ModelState.AddModelError("all", "Problème lors de l'ajout de la postulation, veuillez reessayer!");
                    return View(requetePostulation);
                }
                // Journaliser l'ajout
                _logger.LogInformation($"Ajout de la postulation avec l`Id : {postulation.Id}");
                return RedirectToAction("Index", "OffresEmplois");
            }
            return View(requetePostulation);
        }


        // GET: PostulationsController/Details/5
        [Authorize(Roles = "Admin, RH")]
        [Authorize(Roles = "Admin, Employé")]
        public async Task<ActionResult> Details(int id)
        {
            // Journalisation
            _logger.LogInformation($"Visite de la page Details par l'utilisateur {User.Identity.Name}");

            Postulation? postulation = await _postulationsService.ObtenirSelonId(id);

            if (postulation == null)
                return NotFound();

            return View(postulation);
        }

        //GET: PostulationsController/Edit/5
        [Authorize(Roles = "Admin, RH")]
        [Authorize(Roles = "Admin, Employé")]
        public async Task<ActionResult> Edit(int id)
        {
            Postulation? postulation = await _postulationsService.ObtenirSelonId(id);

            if (postulation == null)
                return NotFound();

            // Journalisation
            _logger.LogInformation($"Visite de la page Edit par l'utilisateur {postulation.IdCandidat}");

            // Verifier si la date de disponibilité est inférieure ou supérieure de 5 jours à la date du jour.
            if (postulation.DateDisponibilite > DateTime.Now.AddDays(-5) && postulation.DateDisponibilite < DateTime.Now.AddDays(5))
            {          
                return BadRequest("Il n’est pas possible de modifier ou supprimer une postulation dont la date de disponibilité est\r\ninférieure ou supérieure de 5 jours à la date du jour.");
            }

            return View(postulation);
        }

        // POST: PostulationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, RH")]
        [Authorize(Roles = "Admin, Employé")]
        public async Task<ActionResult> Edit(Postulation postulation)
        {
            // Obtenir l'utilisateur courant
            IEnumerable<DocumentModel>? documents = _documentsService.ObtenirTout(postulation.IdCandidat).Result;

            // Vérifier si l'utilisateur a un CV
            bool hasCV = false;
            foreach (var document in documents)
            {
                if (document.Type == "CV")
                {
                    hasCV = true;
                    break;
                }
            }
            if (!hasCV)
            {
                // Si aucun CV n'est trouvé, renvoyer un message d'erreur
                ViewBag.ErrorMessage = "Un CV est requis pour postuler. Veuillez télécharger d'abord un CV dans votre espace Documents.";
                ModelState.AddModelError("Error", "Un CV est requis pour postuler. Veuillez télécharger d'abord un CV dans votre espace Documents.");
            }

            // Vérifier si l'utilisateur a une lettre de motivation

ModernRecrut.MVC/Views/OffresEmplois/Create.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Offre d'emploi - Créé";
}

<h1>Créé</h1>

<h4>Offre d'emploi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" value="0" type="hidden" disabled />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDebut" class="control-label"></label>
                <input asp-for="DateDebut" class="form-control" value="@DateTime.Today" />
                <span asp-validation-for="DateDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Créé" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour au offres d'emplois</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModernRecrut.MVC/Views/OffresEmplois/Delete.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Offre d'emploi - Supprimer";
}

<h1>Supprimer</h1>

<h3>Êtes-vous sur de vouloir supprimer cette offre d'emploi?</h3>
<div>
    <h4>Offre d'emploi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDebut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour au offres d'emplois</a>
    </form>
</div>

ModernRecrut.MVC/Views/OffresEmplois/Details.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Offre d'emploi - Details";
}

<h1>Details</h1>

<div>
    <h4>Offre d'emploi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDebut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Modifier", "Edit", new {  id=Model.Id  }) |
    @Html.ActionLink("Supprimer", "Delete", new {  id=Model.Id  }) |
    @Html.ActionLink("Favoris","Create","Favoris", new { id=Model.Id }) |
    @Html.ActionLink("Postuler","Postuler","Postulations", new { id=Model.Id }) |

    <a asp-action="Index">Retour au offres d'emplois</a>
</div>

ModernRecrut.MVC/Views/OffresEmplois/Edit.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Offre d'emploi - Modifier";
}

<h1>Modifier</h1>

<h4>Offre d'emploi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" diabled type="hidden"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDebut" class="control-label"></label>
                <input asp-for="DateDebut" class="form-control"  />
                <span asp-validation-for="DateDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour au offres d'emplois</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModernRecrut.MVC/Views/OffresEmplois/Index.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.OffreEmploi>

@{
    ViewData["Title"] = "Offres d'emplois - Liste";
}

<h1>Liste des offres d'emplois</h1>

<p>
    <a asp-action="Create">Créé une nouvelle offre d'emploi</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Rechercher dans les postes : <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Recherche" class="btn btn-default" style="color:blue" /> |
            <a asp-action="Index">Retour à la liste d'emprunts en cours</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poste)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDebut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateFin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Poste)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateDebut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateFin)
            </td>
            <td>
                @Html.ActionLink("Modifier", "Edit", new {  id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id  }) |
                @Html.ActionLink("Supprimer", "Delete", new {  id=item.Id  }) |
                @Html.ActionLink("Favoris","Create","Favoris", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>